# Generated by Django 4.1.4 on 2023-01-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_author_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
